### ISSUE TITLE
Heroku deploy database error

### ISSUE THREAD

**Issue by byt3smith** [byt3smith/malstrom#1]
There is a problem when deploying the app to Heroku where the application does not fully migrate the db

```

2016-07-11T15:05:15.743269+00:00 app[web.1]: Started GET "/d/login" for 172.89.197.195 at 2016-07-11 15:05:15 +0000
2016-07-11T15:05:15.747006+00:00 app[web.1]: Processing by Devise::SessionsController#new as HTML
2016-07-11T15:05:15.750494+00:00 app[web.1]:                ORDER BY a.attnum
2016-07-11T15:05:15.757992+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2016-07-11T15:05:15.758001+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.0.rc2/lib/active_record/connection_adapters/postgresql_adapter.rb:969:in `column_definitions'
2016-07-11T15:05:15.758012+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0.rc2/lib/active_support/callbacks.rb:113:in `call'
2016-07-11T15:05:15.758021+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0.rc2/lib/active_support/callbacks.rb:166:in `call'
2016-07-11T15:05:15.758026+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0.rc2/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
2016-07-11T15:05:15.758032+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0.rc2/lib/active_support/notifications.rb:159:in `instrument'
2016-07-11T15:05:15.758072+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
2016-07-11T15:05:15.758092+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/railties-4.1.0.rc2/lib/rails/rack/logger.rb:20:in `call'
```

**Comment by byt3smith** [comment]
Issue #1 resolved. rake db:migrate now runs automatically upon deploy.

![success](http://i1.kym-cdn.com/photos/images/facebook/000/011/296/success_baby.jpg)
